language: csharp
solution: OOD.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore OOD.sln
after_script:
  - nunit-console UnitTestProject1/bin/Debug/UnitTestProject1.dll